spring:
  kafka:
    listener:
      missing-topics-fatal: false
    producer:
      bootstrap-servers: ljlhhas.top:17092,ljlhhas.top:17192,ljlhhas.top:17392
      batch-size: 16384  #每次批量发送信息的数量
      buffer-memory: 33554432 #达到该缓冲区大小就发送数据
      key-serializer: org.apache.kafka.common.serialization.StringSerializer #key的序列化器
      value-serializer: org.apache.kafka.common.serialization.StringSerializer #value的序列化器
    #消费者配置
    consumer:
      bootstrap-servers: ljlhhas.top:17192
      enable-auto-commit: true #启用自动提交偏移量 ,ljlhhas.top:17192,ljlhhas.top:17392
      auto-commit-interval: 100 #设置偏移量提交间隔
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer #key的反序列化器
      value-deserializer: org.apache.kafka.common.serialization.StringDeserializer #value的反序列化器
      group-id: test1
  rsocket:
    server:
      transport:
server:
  port: 8081